spring.application.name=Recordario
# POSTGRE
spring.datasource.url=jdbc:postgresql://localhost:5432/recordario
spring.datasource.username=postgres
spring.datasource.password=charles
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.core.env=DEBUG

application.security.jwt.tiempo-expiracion=900000
application.security.jwt.tiempo-expiracion-refresco=604800000
application.security.jwt.codigo-secreto=2vKJqT++YqxUA7dan2hmsRYe5dEk/kgZCDYBn4LiQTE=
